### ISSUE TITLE
Crashes after inputting details 

### ISSUE THREAD

**Issue by ghost** [eslam-allam/POE_whisper#1]
After inputting path, chat_id and bot_id, the program closes and doesn't appear to push

**Comment by eslam-allam** [comment]
Go to the program's folder and find “program_logs.log”. You’ll find the error messages there. So copy and paste the last few lines here for further assistance. Keep in mind that the path to the logs file must include the file name e.g …./logs/Client.txt.

**Comment by ghost** [comment]
Hi, that was the problem. I didn't include Client.txt in the path for the logs.
